---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mq-pv
spec:
  capacity:
    storage: 2Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  nfs:
    path: /data/kubernetes-storageclass
    server: 172.26.17.237
